import { Vocabulary } from './types';

export const fullVocabularyList: Vocabulary[] = [
    { id: 1, en: "awake", tr: "uyanıkken" },
    { id: 2, en: "deep sleep", tr: "derin uyku" },
    { id: 3, en: "store", tr: "mağaza" },
    { id: 4, en: "in advance", tr: "öncesinde" },
    { id: 5, en: "broken plates", tr: "kırık tabaklar" },
    { id: 6, en: "stays up", tr: "ayakta kalmak" },
    { id: 7, en: "relatives", tr: "akraba" },
    { id: 8, en: "whole", tr: "bütün" },
    { id: 9, en: "stripes", tr: "çizgiler" },
    { id: 10, en: "marches", tr: "yürüyüş" },
    { id: 11, en: "bother", tr: "rahatsız etmek" },
    { id: 12, en: "private", tr: "özel / gizli" },
    { id: 13, en: "stand for", tr: "katlanmak" },
    { id: 14, en: "look forward to", tr: "dört gözle beklemek" },
    { id: 15, en: "digit", tr: "basamak" },
    { id: 16, en: "glad", tr: "memnun / mutlu" },
    { id: 17, en: "stunning", tr: "çekici / muhteşem" },
    { id: 18, en: "impressive", tr: "etkileyici" },
    { id: 19, en: "destination", tr: "varış noktası" },
    { id: 20, en: "in addition", tr: "ayrıca" },
    { id: 21, en: "explore", tr: "keşfetmek" },
    { id: 22, en: "treatments", tr: "tedaviler / merkez" },
    { id: 23, en: "landmark", tr: "simge / dönüm noktası" },
    { id: 24, en: "crafts people", tr: "zanaatkarlar" },
    { id: 25, en: "arranged", tr: "ayarlanmış" },
    { id: 26, en: "register", tr: "kayıt olmak" },
    { id: 27, en: "even", tr: "hatta / -e rağmen" },
    { id: 28, en: "impression", tr: "izlenim" },
    { id: 29, en: "benefits", tr: "fayda" },
    { id: 30, en: "contains", tr: "içermek" },
    { id: 31, en: "purchase", tr: "satın almak" },
    { id: 32, en: "taxes", tr: "vergi" },
    { id: 33, en: "balanced", tr: "dengeli" },
    { id: 34, en: "coastal", tr: "sahil" },
    { id: 35, en: "jams", tr: "yoğunluk / reçel" },
    { id: 36, en: "crime", tr: "suç" },
    { id: 37, en: "percent", tr: "yüzde" },
    { id: 38, en: "dwellers", tr: "ikamet edenler" },
    { id: 39, en: "tease", tr: "kışkırtmak" },
    { id: 40, en: "convenient", tr: "uygun" },
    { id: 41, en: "compare", tr: "karşılaştırmak" },
    { id: 42, en: "fabric", tr: "kumaş" },
    { id: 43, en: "improve", tr: "geliştirmek" },
    { id: 44, en: "diabetes", tr: "şeker hastalığı" },
    { id: 45, en: "reduce", tr: "azaltmak" },
    { id: 46, en: "hire", tr: "işe almak" },
    { id: 47, en: "fire", tr: "işten çıkarmak" },
    { id: 48, en: "inappropriate", tr: "uygunsuz" },
    { id: 49, en: "sincere", tr: "samimi" },
    { id: 50, en: "hesitate", tr: "tereddüt etmek" },
    { id: 51, en: "aspect", tr: "yön / açı" },
    { id: 52, en: "regard", tr: "saygınlık" },
    { id: 53, en: "construction", tr: "yapı / inşaat" },
    { id: 54, en: "rob", tr: "soymak" },
    { id: 55, en: "poisoned", tr: "zehirlenmek" },
    { id: 56, en: "however", tr: "ancak" },
    { id: 57, en: "flow", tr: "akış" },
    { id: 58, en: "coral reefs", tr: "mercan kayalıkları" },
    { id: 59, en: "get rid of", tr: "kurtulmak" },
    { id: 60, en: "creatures", tr: "yaratıklar" },
    { id: 61, en: "coherence", tr: "tutarlılık" },
    { id: 62, en: "choppy", tr: "baştan savma" },
    { id: 63, en: "interrupted", tr: "bölünmüş" },
    { id: 64, en: "deduct", tr: "çıkarmak / eksiltmek" },
    { id: 65, en: "rhyme", tr: "kafiye" },
    { id: 66, en: "cans", tr: "konserve" },
    { id: 67, en: "pantry", tr: "kiler" },
    { id: 68, en: "cellar", tr: "kiler / mahzen" },
    { id: 69, en: "pack", tr: "valiz toplamak" },
    { id: 70, en: "mend", tr: "tamir etmek" },
    { id: 71, en: "hardware store", tr: "hırdavatçı" },
    { id: 72, en: "quiet", tr: "sessiz" },
    { id: 73, en: "sights", tr: "gezilmesi gereken yerler" },
    { id: 74, en: "subway", tr: "metro" },
    { id: 75, en: "for instance", tr: "örneğin" },
    { id: 76, en: "out of breath", tr: "nefes nefese" },
    { id: 77, en: "though", tr: "yine de" },
    { id: 78, en: "through", tr: "boyunca / içinden" },
    { id: 79, en: "dawn", tr: "gün doğumu" },
    { id: 80, en: "throughout", tr: "boyunca / süresince" },
    { id: 81, en: "tough", tr: "zor" },
    { id: 82, en: "steal", tr: "çalmak" },
    { id: 83, en: "tear", tr: "yırtmak" },
    { id: 84, en: "sell", tr: "satmak" },
    { id: 85, en: "cash", tr: "peşin" },
    { id: 86, en: "still", tr: "hala" },
    { id: 87, en: "stole", tr: "çaldı (geçmiş)" },
    { id: 88, en: "amount", tr: "miktar" },
    { id: 89, en: "into pieces", tr: "parçalara" },
    { id: 90, en: "meeting", tr: "toplantı" },
    { id: 91, en: "presentation", tr: "sunum" },
    { id: 92, en: "clapped", tr: "alkışladı" },
    { id: 93, en: "hurry up", tr: "acele et" },
    { id: 94, en: "current", tr: "şu anda / akım" },
    { id: 95, en: "close to", tr: "yakın" },
    { id: 96, en: "snorkeling", tr: "şnorkel" },
    { id: 97, en: "wellness", tr: "sağlık" },
    { id: 98, en: "square", tr: "meydan" },
    { id: 99, en: "souvenirs", tr: "hediyelik eşya" },
    { id: 100, en: "cuisine", tr: "mutfak (kültürü)" },
    { id: 101, en: "residence", tr: "kalınan yer" },
    { id: 102, en: "efficient", tr: "etkili" },
    { id: 103, en: "ferries", tr: "vapur" },
    { id: 104, en: "harbor", tr: "liman" },
    { id: 105, en: "lovely resorts", tr: "tatil köyü" },
    { id: 106, en: "accommodation", tr: "konaklama" },
    { id: 107, en: "worth", tr: "değer" },
    { id: 108, en: "railway", tr: "demiryolu" },
    { id: 109, en: "supportive", tr: "desteklemek" },
    { id: 110, en: "internships", tr: "staj" },
    { id: 111, en: "quality", tr: "özellik / kalite" },
    { id: 112, en: "luck", tr: "şans" },
    { id: 113, en: "disease", tr: "hastalık" },
    { id: 114, en: "therefore", tr: "bu yüzden" },
    { id: 115, en: "wraps up", tr: "bağlamak (sonuç)" },
    { id: 116, en: "drawbacks", tr: "dezavantaj" },
    { id: 117, en: "additional", tr: "ekstra olarak" },
    { id: 118, en: "potential", tr: "potansiyel" },
    { id: 119, en: "minor", tr: "önemsiz / küçük" },
    { id: 120, en: "slight", tr: "hor görmek / hafif" },
    { id: 121, en: "in short", tr: "kısaca" },
    { id: 122, en: "issue", tr: "konu / mesele" },
    { id: 123, en: "peril", tr: "büyük tehlike" },
    { id: 124, en: "in conclusion", tr: "sonuç olarak" },
    { id: 125, en: "receive", tr: "almak" },
    { id: 126, en: "devote", tr: "adamak" },
    { id: 127, en: "ruin", tr: "mahvetmek" },
    { id: 128, en: "accident", tr: "kaza" },
    { id: 129, en: "nevertheless", tr: "yine de" },
    { id: 130, en: "divorced", tr: "boşanmak" },
    { id: 131, en: "kindergarten", tr: "anaokulu" },
    { id: 132, en: "engaged", tr: "nişanlı" },
    { id: 133, en: "separate", tr: "ayırmak" },
    { id: 134, en: "fiance", tr: "nişanlı (erkek)" },
    { id: 135, en: "crash", tr: "kaza / çarpma" },
    { id: 136, en: "suffer", tr: "acı çekmek" },
    { id: 137, en: "since", tr: "o zamandan beri / çünkü" },
    { id: 138, en: "faith", tr: "inanç / güven" },
    { id: 139, en: "religious", tr: "dindar" },
    { id: 140, en: "refuse", tr: "reddetmek" },
    { id: 141, en: "association", tr: "dernek" },
    { id: 142, en: "fame", tr: "ün" },
    { id: 143, en: "allow", tr: "izin vermek" },
    { id: 144, en: "eventually", tr: "sonunda" },
    { id: 145, en: "pass away", tr: "vefat etmek" },
    { id: 146, en: "brain", tr: "beyin" },
    { id: 147, en: "implies", tr: "ima etmek" },
    { id: 148, en: "lecture hall", tr: "amfi" },
    { id: 149, en: "logic", tr: "mantık" },
    { id: 150, en: "definition", tr: "tanım" },
    { id: 151, en: "ski", tr: "kayak" },
    { id: 152, en: "comment", tr: "yorum" },
    { id: 153, en: "such as", tr: "örneğin / gibi" },
    { id: 154, en: "make a fire", tr: "ateş yakmak" },
    { id: 155, en: "incredibly", tr: "inanılmaz" },
    { id: 156, en: "possible", tr: "mümkün" },
    { id: 157, en: "massive", tr: "devasa" },
    { id: 158, en: "entrepreneurship", tr: "girişimcilik" },
    { id: 159, en: "premature", tr: "olgunlaşmamış" },
    { id: 160, en: "mature", tr: "olgunlaşmış" },
    { id: 161, en: "thats why", tr: "bu nedenle" },
    { id: 162, en: "volunteer", tr: "gönüllü" },
    { id: 163, en: "trash", tr: "çöp" },
    { id: 164, en: "cough", tr: "öksürmek" },
    { id: 165, en: "preserve", tr: "koruyucu" },
    { id: 166, en: "membership", tr: "üyelik" },
    { id: 167, en: "author", tr: "yazar" },
    { id: 168, en: "poet", tr: "şair" },
    { id: 169, en: "poem", tr: "şiir" },
    { id: 170, en: "seed", tr: "tohum" },
    { id: 171, en: "sculptor", tr: "heykeltraş" },
    { id: 172, en: "schedule", tr: "program" },
    { id: 173, en: "artist", tr: "ressam / sanatçı" },
    { id: 174, en: "record", tr: "kayıt almak" },
    { id: 175, en: "creative", tr: "yaratıcı" },
    { id: 176, en: "nearby", tr: "yakınında" },
    { id: 177, en: "field", tr: "saha / alan" },
    { id: 178, en: "peaceful", tr: "huzurlu / rahatlatıcı" },
    { id: 179, en: "keep in touch", tr: "irtibatta kalmak" },
    { id: 180, en: "shapes", tr: "şekil" },
    { id: 181, en: "mate", tr: "arkadaş" },
    { id: 182, en: "skills", tr: "yetenek" },
    { id: 183, en: "jogging", tr: "tempolu koşu" },
    { id: 184, en: "phrases", tr: "belki / ibare" },
    { id: 185, en: "outline", tr: "taslak" },
    { id: 186, en: "flyers", tr: "afiş" },
    { id: 187, en: "target", tr: "hedef / görev" },
    { id: 188, en: "goal", tr: "görev / amaç" },
    { id: 189, en: "headings", tr: "başlık" },
    { id: 190, en: "sources", tr: "kaynak" },
    { id: 191, en: "departure", tr: "kalkış" },
    { id: 192, en: "lowest", tr: "en düşük" },
    { id: 193, en: "available", tr: "müsait" },
    { id: 194, en: "gardening", tr: "bahçıvanlık" },
    { id: 195, en: "classifieds", tr: "ilan" },
    { id: 196, en: "fewest", tr: "en az" },
    { id: 197, en: "fascinating", tr: "büyüleyici" },
    { id: 198, en: "homeless", tr: "evsiz" },
    { id: 199, en: "charity", tr: "vakıf / hayır kurumu" },
    { id: 200, en: "booked", tr: "rezervasyon" },
    { id: 201, en: "genius", tr: "dahi" },
    { id: 202, en: "grill", tr: "ızgara" },
    { id: 203, en: "mansion", tr: "malikane" },
    { id: 204, en: "mention", tr: "ifade etmek" },
    { id: 205, en: "grocery", tr: "manav / bakkal" },
    { id: 206, en: "poor", tr: "fakir" },
    { id: 207, en: "rich", tr: "zengin" },
    { id: 208, en: "paragliding", tr: "yamaç paraşütü" },
    { id: 209, en: "cheated on", tr: "aldatma" },
    { id: 210, en: "cheat", tr: "hile / aldatmak" },
    { id: 211, en: "hostel", tr: "pansiyon" },
    { id: 212, en: "ancient", tr: "antik" },
    { id: 213, en: "set up a tent", tr: "çadır kurmak" },
    { id: 214, en: "bottom", tr: "alt / dip" },
    { id: 215, en: "stranger", tr: "yabancı" },
    { id: 216, en: "civil engineer", tr: "inşaat mühendisi" },
    { id: 217, en: "assignment", tr: "ödev" },
    { id: 218, en: "charming", tr: "kuralcı / çekici" },
    { id: 219, en: "competition", tr: "yarışma" },
    { id: 220, en: "cozy", tr: "evim gibi / rahat" },
    { id: 221, en: "fireplace", tr: "şömine" },
    { id: 222, en: "take a nap", tr: "şekerleme yapmak" },
    { id: 223, en: "ingredient", tr: "malzemeler" },
    { id: 224, en: "discount", tr: "indirim" },
    { id: 225, en: "include", tr: "içermek" },
    { id: 226, en: "price", tr: "fiyat / ücret" },
    { id: 227, en: "increasing", tr: "fiyatı arttırmak" },
    { id: 228, en: "expresses", tr: "ifade etmek" },
    { id: 229, en: "thought", tr: "düşünce" },
    { id: 230, en: "letters", tr: "harfler / mektuplar" },
    { id: 231, en: "state", tr: "durum" },
    { id: 232, en: "lettuce", tr: "marul" },
    { id: 233, en: "event", tr: "olay" },
    { id: 234, en: "experience", tr: "deneyim" },
    { id: 235, en: "action", tr: "hareket" },
    { id: 236, en: "cereal", tr: "kahvaltılık gevrek" },
    { id: 237, en: "the drums", tr: "bateri" },
    { id: 238, en: "identify", tr: "belirlemek" },
    { id: 239, en: "chases", tr: "kovalamaca" },
    { id: 240, en: "corner", tr: "köşe" },
    { id: 241, en: "bakes", tr: "pişirmek" },
    { id: 242, en: "novels", tr: "roman" },
    { id: 243, en: "oat", tr: "yulaf" },
    { id: 244, en: "sandcastles", tr: "kumdan kale" },
    { id: 245, en: "catches", tr: "yakalamak" },
    { id: 246, en: "coworkers", tr: "iş arkadaşı" },
    { id: 247, en: "observatory", tr: "gözlemevi" },
    { id: 248, en: "observe", tr: "gözlem" },
    { id: 249, en: "formal", tr: "resmi / akademik" },
    { id: 250, en: "continent", tr: "kıta" },
    { id: 251, en: "province", tr: "eyalet" },
    { id: 252, en: "region", tr: "bölge" },
    { id: 253, en: "bowls", tr: "kase" },
    { id: 254, en: "jars", tr: "kavanoz" },
    { id: 255, en: "save money", tr: "para biriktirmek" },
    { id: 256, en: "exception", tr: "istisna" },
    { id: 257, en: "naughty", tr: "yaramaz" },
    { id: 258, en: "recommend", tr: "öneri yapmak" },
    { id: 259, en: "interview", tr: "röportaj" },
    { id: 260, en: "probably", tr: "muhtemelen" },
    { id: 261, en: "contain", tr: "içermek" },
    { id: 262, en: "official", tr: "resmi" },
    { id: 263, en: "basil", tr: "fesleğen" },
    { id: 264, en: "pretty", tr: "oldukça / hoş" },
    { id: 265, en: "here you are", tr: "işte buyrun" },
    { id: 266, en: "shall", tr: "yapalım mı? (öneri)" },
    { id: 267, en: "explain", tr: "açıklamak" },
    { id: 268, en: "pay attention", tr: "dikkat etmek" },
    { id: 269, en: "take care", tr: "dikkat et" },
    { id: 270, en: "wales", tr: "galler" },
    { id: 271, en: "hungary", tr: "macaristan" },
    { id: 272, en: "receding", tr: "kelleşmek (saç)" },
    { id: 273, en: "niece", tr: "kız yeğen" },
    { id: 274, en: "nephew", tr: "erkek yeğen" },
    { id: 275, en: "daughter in law", tr: "gelin" },
    { id: 276, en: "blond", tr: "sarışın" },
    { id: 277, en: "describe", tr: "tanımlamak" },
    { id: 278, en: "as well as", tr: "ek olarak" },
    { id: 279, en: "intensive", tr: "yoğun" },
    { id: 280, en: "suburbs", tr: "banliyö" },
    { id: 281, en: "summary", tr: "özet" },
    { id: 282, en: "interpreter", tr: "tercüman" },
    { id: 283, en: "profession", tr: "meslek" },
    { id: 284, en: "fictional", tr: "kurgusal" },
    { id: 285, en: "title", tr: "başlık" },
    { id: 286, en: "son in law", tr: "damat" },
    { id: 287, en: "father in law", tr: "kayınbaba" },
    { id: 288, en: "mother in law", tr: "kaynana" },
    { id: 289, en: "sister in law", tr: "yenge / görümce" },
    { id: 290, en: "grandson", tr: "erkek torun" },
    { id: 291, en: "granddaughter", tr: "kız torun" },
    { id: 292, en: "gerund", tr: "isim fiil" },
    { id: 293, en: "solving", tr: "çözmek" },
    { id: 294, en: "synonym", tr: "eş anlamlı" },
    { id: 295, en: "experiment", tr: "deneyim" },
    { id: 296, en: "antonym", tr: "zıt anlam" },
    { id: 297, en: "another", tr: "başka biri" },
    { id: 298, en: "borrow", tr: "ödünç almak" },
    { id: 299, en: "lend", tr: "ödünç vermek" },
    { id: 300, en: "parking lot", tr: "otopark" },
    { id: 301, en: "bosphorus", tr: "boğaz" },
    { id: 302, en: "opportunity", tr: "imkan" },
    { id: 303, en: "actually", tr: "aslında" },
    { id: 304, en: "view", tr: "manzara" },
    { id: 305, en: "review", tr: "değerlendirmek" },
    { id: 306, en: "pitch", tr: "saha" },
    { id: 307, en: "dormitory", tr: "yurt" },
    { id: 308, en: "royals", tr: "soylular" },
    { id: 309, en: "employers", tr: "iş verenler" },
    { id: 310, en: "concepts", tr: "kavramlar" },
    { id: 311, en: "sequential", tr: "sıralı" },
    { id: 312, en: "awareness", tr: "farkındalık / bilinç" },
    { id: 313, en: "anxious", tr: "anksiyete" },
    { id: 314, en: "foreigner", tr: "yabancı" },
    { id: 315, en: "judge", tr: "yargılamak" },
    { id: 316, en: "interference", tr: "müdahale" },
    { id: 317, en: "misunderstanding", tr: "yanlış anlaşılma" },
    { id: 318, en: "simultaneous", tr: "aynı anda" },
    { id: 319, en: "various", tr: "çeşitli" },
    { id: 320, en: "deal with", tr: "başa çıkmak" },
    { id: 321, en: "necessary", tr: "gerekli" },
    { id: 322, en: "consequences", tr: "sonuçlar" },
    { id: 323, en: "statement", tr: "ifade" },
    { id: 324, en: "ability", tr: "yetenek" },
    { id: 325, en: "process", tr: "süreç" },
    { id: 326, en: "nightowl", tr: "gece kuşu" },
    { id: 327, en: "early bird", tr: "erkenci kuş" },
    { id: 328, en: "daydreams", tr: "hayal kurmak" },
    { id: 329, en: "lonely", tr: "yalnız" },
    { id: 330, en: "during", tr: "sırasında" },
    { id: 331, en: "pillow", tr: "yastık" },
    { id: 332, en: "nightmare", tr: "kabus" },
    { id: 333, en: "expert", tr: "usta / uzman" },
    { id: 334, en: "subconsciousness", tr: "bilinç altı" },
    { id: 335, en: "rapid", tr: "hızlı" },
    { id: 336, en: "whats more", tr: "dahası" },
    { id: 337, en: "flexible", tr: "uyumlu / esnek" },
    { id: 338, en: "explorer", tr: "kaşif" },
    { id: 339, en: "polar", tr: "kutup" },
    { id: 340, en: "hill", tr: "tepe" },
    { id: 341, en: "results", tr: "sonuç" },
    { id: 342, en: "sunrise", tr: "gün doğumu" },
    { id: 343, en: "each", tr: "her biri" },
    { id: 344, en: "clues", tr: "delil / ipuçları" },
    { id: 345, en: "heathrow", tr: "havaalanı (london)" },
    { id: 346, en: "boarding pass", tr: "biniş kartı" },
    { id: 347, en: "to board", tr: "binmek" },
    { id: 348, en: "departures", tr: "kalkış tabelası" },
    { id: 349, en: "duty free shop", tr: "vergisiz mağaza" },
    { id: 350, en: "drug sniffer dog", tr: "uyuşturucu arama köpeği" },
    { id: 351, en: "to land", tr: "inmek" },
    { id: 352, en: "landing", tr: "iniş" },
    { id: 353, en: "passenger", tr: "yolcu" },
    { id: 354, en: "runway", tr: "pist" },
    { id: 355, en: "security", tr: "güvenlik" },
    { id: 356, en: "to take off", tr: "kalkması (aracın)" },
    { id: 357, en: "take-off", tr: "kalkış" },
    { id: 358, en: "trolley", tr: "bagaj arabası" },
    { id: 359, en: "destinations", tr: "varış yeri" },
    { id: 360, en: "incident", tr: "olay / hadise" },
    { id: 361, en: "distances", tr: "mesafeler" },
    { id: 362, en: "heart attack", tr: "kalp krizi" },
    { id: 363, en: "alert", tr: "uyarı" },
    { id: 364, en: "handles", tr: "idare etmek" },
    { id: 365, en: "on standby", tr: "hazırda beklemek" },
    { id: 366, en: "remove", tr: "kaldırmak / çıkarmak" },
    { id: 367, en: "puts out", tr: "söndürmek" },
    { id: 368, en: "candles", tr: "mum" },
    { id: 369, en: "difficult situation", tr: "zor durum" },
    { id: 370, en: "runs", tr: "şirketi yönetmek" },
    { id: 371, en: "impatient", tr: "sabırsız" },
    { id: 372, en: "extinguish", tr: "söndürmek" },
    { id: 373, en: "satisfied", tr: "tatmin olmuş" },
    { id: 374, en: "earn", tr: "kazanmak" },
    { id: 375, en: "flavour", tr: "aroma" },
    { id: 376, en: "present", tr: "hediye" },
    { id: 377, en: "civil servant", tr: "memur" },
    { id: 378, en: "instead", tr: "yerine" },
    { id: 379, en: "stunt", tr: "dublör" },
    { id: 380, en: "martial art", tr: "dövüş sanatı" },
    { id: 381, en: "affordable", tr: "uygun fiyatlı" },
    { id: 382, en: "bracelet", tr: "bilezik" },
    { id: 383, en: "bargain", tr: "pazarlık" },
    { id: 384, en: "roaring", tr: "küpe" },
    { id: 385, en: "blue bead", tr: "nazar boncuğu" },
    { id: 386, en: "maiden tower", tr: "kız kulesi" },
    { id: 387, en: "jewelry", tr: "mücevher" },
    { id: 388, en: "stall", tr: "tezgah / dükkan" },
    { id: 389, en: "fortune", tr: "servet" },
    { id: 390, en: "rush", tr: "acele" },
    { id: 391, en: "luggage", tr: "bagaj" },
    { id: 392, en: "mystery", tr: "gizli" },
    { id: 393, en: "president", tr: "başkan" },
    { id: 394, en: "includes", tr: "dahil" },
    { id: 395, en: "currency", tr: "para birimi" },
    { id: 396, en: "aimed", tr: "hedeflemek" },
    { id: 397, en: "candidates", tr: "adaylar" },
    { id: 398, en: "pulled", tr: "demlemek" },
    { id: 399, en: "appearance", tr: "dış görünüş" },
    { id: 400, en: "outlet", tr: "hizmet" },
    { id: 401, en: "addict", tr: "bağımlı" },
    { id: 402, en: "obsessed", tr: "takıntılı" },
    { id: 403, en: "land", tr: "uçağın inmesi" },
    { id: 404, en: "revolution", tr: "devrim" },
    { id: 405, en: "survey", tr: "anket" },
    { id: 406, en: "valuable", tr: "değerli" },
    { id: 407, en: "murderer", tr: "katil" },
    { id: 408, en: "dietician", tr: "diyetisyen" },
    { id: 409, en: "smoke", tr: "duman" },
    { id: 410, en: "miner", tr: "madenci" },
    { id: 411, en: "prison officer", tr: "gardiyan" },
    { id: 412, en: "cope with", tr: "başa çıkmak" },
    { id: 413, en: "anymore", tr: "artık" },
    { id: 414, en: "bribe", tr: "rüşvet" },
    { id: 415, en: "deal", tr: "anlaşma" },
    { id: 416, en: "cause", tr: "sebep olmak" },
    { id: 417, en: "rub", tr: "ovmak" },
    { id: 418, en: "smooth", tr: "pürüzsüz" }
];
