export interface Vocabulary {
  id: number;
  en: string;
  tr: string;
  sentence?: string; // Optional: generated by AI
}

export interface SRSData {
  level: number;
  nextReview: number; // Timestamp
}

export interface AIValidationResult {
  score: 'iyi' | 'orta' | 'zayıf';
  explanation: string;
  corrected: string;
}

export enum DifficultyLevel {
  A2 = 'A2',
  B1 = 'B1',
  B2 = 'B2'
}
